In [1]:
import pandas as pd 
import numpy as np

from nltk import word_tokenize
import nltk

In [2]:
import re


In [3]:
text = """Fusce risus ex, posuere at ante at, condimentum vestibulum nunc. Proin dapibus egestas neque, a tempor odio pharetra eget. Nullam tempus felis eu consectetur tincidunt. Integer fermentum eu quam vitae tempus. Vivamus volutpat ut dui vitae sollicitudin. Donec ornare dolor a vestibulum pharetra. Mauris eget dui sapien. Mauris lobortis feugiat neque, nec congue leo viverra semper. In vel mauris nunc. Aenean scelerisque arcu a varius tempor. Proin quis nisi et mi dictum tempor. Pellentesque mattis risus metus, id luctus orci ultrices ac. Praesent bibendum lectus a nisl mollis, eu suscipit eros pretium.
Phasellus vitae elit efficitur, varius felis id, vulputate neque. Praesent dictum nunc in velit lobortis tempus. Duis pulvinar ut urna eget volutpat. In hac habitasse platea dictumst. Aenean eros libero, ultrices eu dolor id, ultrices bibendum mauris. Nunc quis nunc feugiat, dapibus sem eget, pretium orci. Mauris mauris felis, pulvinar nec dapibus in, laoreet ac nibh. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. In sed scelerisque massa. Morbi sit amet ex erat. Duis sit amet laoreet ipsum. Nullam rutrum dapibus metus id sollicitudin. Sed lorem metus, maximus id maximus ac, vehicula vitae neque.
Curabitur vestibulum lorem diam, nec dictum lectus sodales id. Morbi at dui at ex fermentum porttitor sit amet et ipsum. Nullam et nibh vitae arcu porta pretium. Aenean ultricies bibendum nibh vitae mattis. Donec nec dignissim lorem. Vivamus ut lectus nec sem suscipit gravida. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Proin nec metus at sapien tempor ultrices. Donec sed orci ante. Quisque finibus maximus justo, sit amet dignissim justo ornare ut. Morbi imperdiet sagittis tristique. Nunc vestibulum velit eget neque ultrices, sit amet egestas elit eleifend.
Curabitur facilisis elementum ligula vitae pellentesque. Nulla facilisi. Nulla vel tristique arcu. Sed dictum nisl ac laoreet venenatis. Proin eros est, suscipit id sodales eu, semper maximus eros. Sed maximus id nulla vel auctor. Nullam libero odio, auctor eget felis et, viverra gravida nisl. Vivamus sed luctus eros, nec mattis leo. Phasellus eget accumsan justo. Proin nisl sem, luctus ut gravida consequat, congue sit amet arcu."""

In [4]:
text

'Fusce risus ex, posuere at ante at, condimentum vestibulum nunc. Proin dapibus egestas neque, a tempor odio pharetra eget. Nullam tempus felis eu consectetur tincidunt. Integer fermentum eu quam vitae tempus. Vivamus volutpat ut dui vitae sollicitudin. Donec ornare dolor a vestibulum pharetra. Mauris eget dui sapien. Mauris lobortis feugiat neque, nec congue leo viverra semper. In vel mauris nunc. Aenean scelerisque arcu a varius tempor. Proin quis nisi et mi dictum tempor. Pellentesque mattis risus metus, id luctus orci ultrices ac. Praesent bibendum lectus a nisl mollis, eu suscipit eros pretium.\nPhasellus vitae elit efficitur, varius felis id, vulputate neque. Praesent dictum nunc in velit lobortis tempus. Duis pulvinar ut urna eget volutpat. In hac habitasse platea dictumst. Aenean eros libero, ultrices eu dolor id, ultrices bibendum mauris. Nunc quis nunc feugiat, dapibus sem eget, pretium orci. Mauris mauris felis, pulvinar nec dapibus in, laoreet ac nibh. Pellentesque habitant

In [5]:
# deixa todas as letras minúsculas
text_min = text.lower()

In [6]:
text_min

'fusce risus ex, posuere at ante at, condimentum vestibulum nunc. proin dapibus egestas neque, a tempor odio pharetra eget. nullam tempus felis eu consectetur tincidunt. integer fermentum eu quam vitae tempus. vivamus volutpat ut dui vitae sollicitudin. donec ornare dolor a vestibulum pharetra. mauris eget dui sapien. mauris lobortis feugiat neque, nec congue leo viverra semper. in vel mauris nunc. aenean scelerisque arcu a varius tempor. proin quis nisi et mi dictum tempor. pellentesque mattis risus metus, id luctus orci ultrices ac. praesent bibendum lectus a nisl mollis, eu suscipit eros pretium.\nphasellus vitae elit efficitur, varius felis id, vulputate neque. praesent dictum nunc in velit lobortis tempus. duis pulvinar ut urna eget volutpat. in hac habitasse platea dictumst. aenean eros libero, ultrices eu dolor id, ultrices bibendum mauris. nunc quis nunc feugiat, dapibus sem eget, pretium orci. mauris mauris felis, pulvinar nec dapibus in, laoreet ac nibh. pellentesque habitant

In [7]:
apenas_letras = re.findall(r'[a-zéóáêâãõç\n]+', text_min)

In [8]:
apenas_letras

['fusce',
 'risus',
 'ex',
 'posuere',
 'at',
 'ante',
 'at',
 'condimentum',
 'vestibulum',
 'nunc',
 'proin',
 'dapibus',
 'egestas',
 'neque',
 'a',
 'tempor',
 'odio',
 'pharetra',
 'eget',
 'nullam',
 'tempus',
 'felis',
 'eu',
 'consectetur',
 'tincidunt',
 'integer',
 'fermentum',
 'eu',
 'quam',
 'vitae',
 'tempus',
 'vivamus',
 'volutpat',
 'ut',
 'dui',
 'vitae',
 'sollicitudin',
 'donec',
 'ornare',
 'dolor',
 'a',
 'vestibulum',
 'pharetra',
 'mauris',
 'eget',
 'dui',
 'sapien',
 'mauris',
 'lobortis',
 'feugiat',
 'neque',
 'nec',
 'congue',
 'leo',
 'viverra',
 'semper',
 'in',
 'vel',
 'mauris',
 'nunc',
 'aenean',
 'scelerisque',
 'arcu',
 'a',
 'varius',
 'tempor',
 'proin',
 'quis',
 'nisi',
 'et',
 'mi',
 'dictum',
 'tempor',
 'pellentesque',
 'mattis',
 'risus',
 'metus',
 'id',
 'luctus',
 'orci',
 'ultrices',
 'ac',
 'praesent',
 'bibendum',
 'lectus',
 'a',
 'nisl',
 'mollis',
 'eu',
 'suscipit',
 'eros',
 'pretium',
 '\nphasellus',
 'vitae',
 'elit',
 'efficitu

In [9]:
# junta o texto, já que o .findall separa em tokens
novo_texto = " ".join(apenas_letras)

print(novo_texto)

fusce risus ex posuere at ante at condimentum vestibulum nunc proin dapibus egestas neque a tempor odio pharetra eget nullam tempus felis eu consectetur tincidunt integer fermentum eu quam vitae tempus vivamus volutpat ut dui vitae sollicitudin donec ornare dolor a vestibulum pharetra mauris eget dui sapien mauris lobortis feugiat neque nec congue leo viverra semper in vel mauris nunc aenean scelerisque arcu a varius tempor proin quis nisi et mi dictum tempor pellentesque mattis risus metus id luctus orci ultrices ac praesent bibendum lectus a nisl mollis eu suscipit eros pretium 
phasellus vitae elit efficitur varius felis id vulputate neque praesent dictum nunc in velit lobortis tempus duis pulvinar ut urna eget volutpat in hac habitasse platea dictumst aenean eros libero ultrices eu dolor id ultrices bibendum mauris nunc quis nunc feugiat dapibus sem eget pretium orci mauris mauris felis pulvinar nec dapibus in laoreet ac nibh pellentesque habitant morbi tristique senectus et netus 

In [10]:
# Importando o CountVectorizer
from sklearn.feature_extraction.text import CountVectorizer

In [11]:
vectorizer = CountVectorizer()

In [12]:
vectorizer.fit(apenas_letras)

CountVectorizer()

In [13]:
print(vectorizer.vocabulary_)

{'fusce': 46, 'risus': 105, 'ex': 38, 'posuere': 97, 'at': 8, 'ante': 5, 'condimentum': 12, 'vestibulum': 135, 'nunc': 86, 'proin': 100, 'dapibus': 18, 'egestas': 28, 'neque': 78, 'tempor': 120, 'odio': 87, 'pharetra': 92, 'eget': 29, 'nullam': 85, 'tempus': 121, 'felis': 42, 'eu': 37, 'consectetur': 14, 'tincidunt': 122, 'integer': 56, 'fermentum': 43, 'quam': 102, 'vitae': 136, 'vivamus': 137, 'volutpat': 139, 'ut': 129, 'dui': 25, 'sollicitudin': 117, 'donec': 24, 'ornare': 89, 'dolor': 23, 'mauris': 71, 'sapien': 108, 'lobortis': 65, 'feugiat': 44, 'nec': 77, 'congue': 13, 'leo': 61, 'viverra': 138, 'semper': 112, 'in': 54, 'vel': 132, 'aenean': 3, 'scelerisque': 109, 'arcu': 7, 'varius': 130, 'quis': 103, 'nisi': 81, 'et': 36, 'mi': 74, 'dictum': 20, 'pellentesque': 90, 'mattis': 70, 'metus': 73, 'id': 52, 'luctus': 67, 'orci': 88, 'ultrices': 126, 'ac': 0, 'praesent': 98, 'bibendum': 10, 'lectus': 60, 'nisl': 82, 'mollis': 75, 'suscipit': 118, 'eros': 34, 'pretium': 99, 'phasellu

In [14]:
matrix = vectorizer.transform(apenas_letras)

In [15]:
print(matrix.shape)

(350, 141)


In [16]:
print(matrix.toarray())

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [17]:
df = pd.DataFrame(vectorizer.vocabulary_, index=[0])
df

fusce  risus  ex  posuere  at  ante  condimentum  vestibulum  nunc  proin  \
0     46    105  38       97   8     5           12         135    86    100   

   ...  facilisis  elementum  ligula  nulla  facilisi  venenatis  est  auctor  \
0  ...         40         31      63     84        39        134   35       9   

   accumsan  consequat  
0         1         15  

[1 rows x 141 columns]

In [18]:
frases = text_min.split('\n')
frases

['fusce risus ex, posuere at ante at, condimentum vestibulum nunc. proin dapibus egestas neque, a tempor odio pharetra eget. nullam tempus felis eu consectetur tincidunt. integer fermentum eu quam vitae tempus. vivamus volutpat ut dui vitae sollicitudin. donec ornare dolor a vestibulum pharetra. mauris eget dui sapien. mauris lobortis feugiat neque, nec congue leo viverra semper. in vel mauris nunc. aenean scelerisque arcu a varius tempor. proin quis nisi et mi dictum tempor. pellentesque mattis risus metus, id luctus orci ultrices ac. praesent bibendum lectus a nisl mollis, eu suscipit eros pretium.',
 'phasellus vitae elit efficitur, varius felis id, vulputate neque. praesent dictum nunc in velit lobortis tempus. duis pulvinar ut urna eget volutpat. in hac habitasse platea dictumst. aenean eros libero, ultrices eu dolor id, ultrices bibendum mauris. nunc quis nunc feugiat, dapibus sem eget, pretium orci. mauris mauris felis, pulvinar nec dapibus in, laoreet ac nibh. pellentesque habi

In [19]:
t = vectorizer.transform(frases)

In [20]:
print(t.toarray())

[[1 0 0 1 0 1 0 1 2 0 1 0 1 1 1 0 0 0 1 0 1 0 0 1 1 2 0 0 1 2 0 0 0 0 1 0
  1 3 1 0 0 0 1 1 1 0 1 0 0 0 0 0 1 0 1 0 1 0 0 0 1 1 0 0 0 1 0 1 0 0 1 3
  0 1 1 1 0 1 2 0 0 1 1 0 0 1 2 1 1 1 1 0 2 0 0 0 0 1 1 1 2 0 1 1 0 2 0 0
  1 1 0 0 1 0 0 0 0 1 1 0 3 2 1 0 0 0 1 0 0 1 1 0 1 0 0 2 2 1 1 1 0]
 [3 0 0 1 2 0 0 0 0 0 1 0 0 0 0 0 0 0 3 0 1 1 0 1 0 0 2 1 1 2 0 0 1 1 1 0
  2 1 1 0 0 1 2 0 1 0 0 0 1 1 1 0 4 0 4 0 0 1 0 2 0 0 1 0 0 1 1 0 1 1 0 3
  2 2 0 0 2 1 2 1 1 0 0 0 0 1 3 0 1 0 1 0 0 1 1 0 0 0 1 1 0 2 0 1 0 0 1 0
  0 1 2 1 0 1 2 0 0 1 0 0 0 1 0 0 1 1 2 0 1 1 1 1 0 1 0 0 2 0 0 1 1]
 [0 0 1 1 3 1 1 1 3 0 1 1 0 0 0 0 1 1 0 1 1 0 2 0 2 1 0 0 1 1 1 0 1 0 0 0
  2 0 1 0 0 0 0 1 0 1 0 1 0 0 0 1 1 1 0 1 0 1 2 0 2 0 0 0 1 0 2 0 0 0 1 0
  1 1 0 0 2 4 1 0 2 0 0 1 0 1 1 0 1 1 0 2 0 0 0 1 1 0 0 1 1 0 0 0 1 0 0 1
  1 0 1 1 0 0 3 1 1 0 1 1 1 0 0 1 1 0 2 1 0 2 0 0 0 1 0 2 2 1 0 0 0]
 [1 1 0 0 1 0 0 2 0 2 0 0 0 1 0 1 0 1 0 0 1 0 0 0 0 0 0 0 0 2 0 1 0 0 3 1
  1 1 0 1 1 0 1 0 0 0 0 2 0 0 0 0 2 0 0 0 0 0 1 1 0 1

In [21]:
pd.DataFrame(t.toarray(), columns=vectorizer.get_feature_names())

ac  accumsan  ad  aenean  amet  ante  aptent  arcu  at  auctor  ...  \
0   1         0   0       1     0     1       0     1   2       0  ...   
1   3         0   0       1     2     0       0     0   0       0  ...   
2   0         0   1       1     3     1       1     1   3       0  ...   
3   1         1   0       0     1     0       0     2   0       2  ...   

   vehicula  vel  velit  venenatis  vestibulum  vitae  vivamus  viverra  \
0         0    1      0          0           2      2        1        1   
1         1    0      1          0           0      2        0        0   
2         0    0      1          0           2      2        1        0   
3         0    2      0          1           0      1        1        1   

   volutpat  vulputate  
0         1          0  
1         1          1  
2         0          0  
3         0          0  

[4 rows x 141 columns]